Friendship v1
Morrism1/ror-social-scaffold pull request #2
Opened 2020-11-05 15:43 UTC by Morrism1

# Milestone 5: Friendship V1

* Created friendship Invitation model
* Added associations between user and friendship invitation models
* Added new routes to send a friendship invitation features
* Added button link to request friendship in users views
* Added links to accept or decline the friendship in friendship's index page
* Added integration and unit tests with RSpec, capybara, and shoulda for all the features and methods
* You can run rails DB:SEED for a quick 15 users creation with faker gem 👌

2020-11-05 18:36 UTC, tirthajyoti-ghosh requested changes
# Changes required 🛑 

## What a remarkable project you have built 💯! This is impressive 🤩👌🧨!

### But in order to get it approved, we need to work on some changes. Let's see...

- You have missed a couple of tests. Please add tests for the remaining models:
  - [ ] `comment`
  - [ ] `like`
  - [ ] `post`

  Please add controller tests. There are currently no controller tests.

- Right now, the timeline displays posts from all users. As per the requirements of the project, the timeline should display posts from the logged-in user and the user's friends (users who have accepted the logged-in user's friend request) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

  - [ ] Please implement this functionality.

Your project looks absolutely fantastic. Just make these changes and apply for another code review.

Happy coding 👨‍💻 

*Need help? Shoot me a message on Slack - [@Ghosh](https://app.slack.com/client/T47CT8XPG/DRDM6LAQN/user_profile/URB1MHXK6)*
<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

2020-11-05 18:36 UTC, tirthajyoti-ghosh commented on app/helpers/friendship_invitations_helper.rb
> +    current_user.friendship_invitations.find_by(friend_id: user.id).nil?
`find_by` method queries the database to find a row with given constraints. That means it's processing data (application logic), which doesn't belong in "helpers". Helpers are reserved for putting the view logic, not the application logic.

Application logic belongs in the `model`. Please move this logic to the model and use it in controllers. Everything connected with data processing should be encapsulated in models and used in controllers.

2020-11-05 18:36 UTC, tirthajyoti-ghosh commented on app/helpers/friendship_invitations_helper.rb
> +  end
Please do the same thing for this method as well. Please move this logic to the model and use it in controllers.

_**Remember** to update your tests!_

2020-11-05 18:36 UTC, tirthajyoti-ghosh commented on app/views/layouts/application.html.erb
>        <% else %>
Please remove all logic from views. There should be absolutely no logic in views. Instead, outsource all your logic to helpers. There are two more `if` statements below this. Remove them as well.

**Resources**
- [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
- [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
- [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright

2020-11-07 04:52 UTC, trekab approved these changes
### Approved! :tada: 
Well done @Morrism1! Nice job implementing the suggested changes. You may proceed to the next milestone.

_Happy coding!_ :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

2020-11-07 05:11 UTC, merged